version: '3'
services:
    nginx:
        image: nginx:latest
        # 端口映射
        ports:
            - "80:80"
        # 依赖关系 先跑php
        depends_on:
            - "php"
        # 数据卷
        volumes:
            # 映射主机./conf.d目录到容器/etc/nginx/conf.d目录
            - "$PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "$PWD/html:/usr/share/nginx/html"
        # networks:
        #     - app_net
        # 容器名称
        restart: always
    php:
        build: ./php-mysqli
        # image指定build Dockerfile生成镜像的名称
        image: php:7.2-fpm-mysqli
        ports:
            - "9000:9000"
        volumes:
            - "$PWD/html:/var/www/html"
        # networks:
        #     - app_net
        restart: always

    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        # 环境变量
        environment:
            # mysql密码
            - MYSQL_ROOT_PASSWORD=yourpassword
        # networks:
        #     app_net:
        #         # 固定子网ip，网段必须在子网络10.10.*.*
        #         ipv4_address: 10.10.10.1
        restart: always
# networks:
#     # 配置docker network
#     app_net:
#         driver: bridge
#         ipam:
#             config:
#                 # 子网络
#                 - subnet: 10.10.0.0/16